name: "bidi2pdf_demo"

services:
  remote-chrome:
    image: dieters877565/chromedriver:latest
    environment:
      ENABLE_XVFB: true
      ENABLE_VNC: true
      VNC_PASS: supersecret
    ports:
      - 5900:5900

  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  
